version: "3.9"
services:
  server:
    build:  ./server
    ports: 
    - "5000:5000"
    volumes: 
    - ./server:/app
    environment: 
      FLASK_ENV: development
    depends_on:
      - db

  web:
    build: ./client
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/user/src/app
    depends_on: 
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    db-data:
